import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Sidebar from './sidebar'

export default function Layout({ children }) {
    return (
        <div>
            <Head>
                <title>Answers Galore</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.headerContainer}>
                <h1 className={styles.title}>Answers Galore</h1>
                <div id="titlePositioner" style={{ marginTop: "20px" }}>
                    <div id="displayUsername"></div><span id="displayPoints"></span><div id="displayLogout" style={{ display: "none" }}><Link href={'/logout'} passHref><button>Logout</button></Link></div>
                    <div id="displayButtons">
                        <Link href={'/login'} passHref><button>Login</button></Link>
                        <Link href={'/register'} passHref><button>Register</button></Link>
                    </div>
                </div>
            </header>
            <main className={styles.container}>
                <Sidebar />
                <div className={styles.mainContainer}>
                    {children}
                </div>
            </main>
        </div>
    )
}