import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <head>
        <title>Answers Galore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <header className={styles.headerContainer}>
        <h1 className={styles.title}>Answers Galore</h1>
      </header>
      <main className={styles.container}>
        <aside>
          <nav>
            <ul className={styles.navContainer}>
              <li className={styles.navItem}>Category 1</li>
              <li className={styles.navItem}>Category 2</li>
              <li className={styles.navItem}>Category 3</li>
              <li className={styles.navItem}>Category 4</li>
              <li className={styles.navItem}>Category 5</li>
            </ul>
          </nav>
        </aside>
        <div>

        </div>
      </main>

      <footer>

      </footer>
    </div>
  )
}
