import { calculateObjectSize } from 'bson'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <head>
        <title>Answers Galore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <header className={styles.headerContainer}>
        <h1 className={styles.title}>Answers Galore</h1>
      </header>
      <main className={styles.container}>
        <aside>
          <ul>
            <nav className={styles.navContainer}>
              <div className={styles.navItem}><li style={{marginTop: "50px"}}>Category 1</li></div>
              <div className={styles.navItem}><li style={{marginTop: "50px"}}>Category 2</li></div>
              <div className={styles.navItem}><li style={{marginTop: "50px"}}>Category 3</li></div>
              <div className={styles.navItem}><li style={{marginTop: "50px"}}>Category 4</li></div>
              <div className={styles.navItem}><li style={{marginTop: "50px"}}>Category 5</li></div>
            </nav>
          </ul>
        </aside>
        <div>

        </div>
      </main>

      <footer>

      </footer>
    </div>
  )
}
